INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToLogin');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToRegister');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToAddEmployee');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToBOHome');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToCustomerHome');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToEmployeeTimes');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToEmployeeService');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToBusinessHours');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToSUHome');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToBusinessRegister');
INSERT INTO `permissionKey`(`id`,`key`) VALUES (NULL,'canGoToModifyServices')